FROM node:slim
WORKDIR /app
#COPY package.json /app
ENV http_proxy 'http://guduru.reddy:sras@2018@btpproxy.mphasis.com:8080'
ENV https_proxy 'http://guduru.reddy:sras@2018@btpproxy.mphasis.com:8080'

COPY . /app

RUN npm config set proxy http://btpproxy.mphasis.com:8080 
RUN npm config set https-proxy http://btpproxy.mphasis.com:8080
RUN npm config set strict-ssl false

RUN npm install

CMD npm run dev:server

EXPOSE 3000
