FROM microsoft/dotnet:2.0-runtime AS base
WORKDIR /app

FROM microsoft/dotnet:2.0-sdk AS build
WORKDIR /src
COPY TestConsole/TestConsole.csproj TestConsole/
RUN dotnet restore TestConsole/TestConsole.csproj
COPY . .
WORKDIR /src/TestConsole
RUN dotnet build TestConsole.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish TestConsole.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "TestConsole.dll"]
