FROM openjdk:8-jdk-alpine

LABEL maintainer="Sanit.Dhar@mphasis.com"

# The application's jar file
ARG JAR_FILE=target/STP.war

ARG TEMPLATES=email-templates/hello-world.html

# Add the application's jar to the container
ADD ${JAR_FILE} /usr/local/STP.war
ADD ${TEMPLATES} /email-templates/hello-world.html

# Run the jar file 
ENTRYPOINT ["java","-jar","/usr/local/STP.war"]

EXPOSE 8899