# Pull base image
FROM tomcat:9.0.2-jre8

# Maintainer
MAINTAINER "NagiReddy <nagireddy.guduru@gmail.com">
#ENV http_proxy 'http://guduru.reddy:sonu%402018@btpproxy.mphasis.com:8080'
#ENV https_proxy 'http://guduru.reddy:sonu%402018@btpproxy.mphasis.com:8080'


#COPY tomcat-users.xml /usr/local/tomcat/conf/tomcat-users.xml

ADD 18-01-2018/DigitalReadinessAssessmentTool-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/

#Place the External Property file 
ADD 18-01-2018/application.properties /usr/local/tomcat/
ADD 18-01-2018/application.properties /usr/local/tomcat/conf/




	